import test from 'node:test';
import assert from 'node:assert/strict';
import { applyCommandAction } from '../src/lib/command-state/actions';
import { commandStateSeed, type CommandWorkItem } from '../src/data/command-center-state';
const order: CommandWorkItem = {id:'test-order',title:'Test fixture only',lane:'Engineering',status:'Needs B Approval',priority:'P1',why:'Test state transitions',expectedImpact:'Reliable actions',proofRequired:'Tests pass',owner:'Slim',dueOrCadence:'This week',links:[],metricToWatch:'Test failures',completionEvidence:''};
const base = () => ({...structuredClone(commandStateSeed),workItems:[structuredClone(order)],commandLog:[]});
const apply = (state: ReturnType<typeof base>, body: Record<string,unknown>) => applyCommandAction(state,body,'2026-09-15T04:00:00.000Z','fixture-event');
test('approve requires reason',()=>assert.throws(()=>apply(base(),{action:'approve',workItemId:order.id}),/reason/));
test('approve records scoped verdict and audit, without execution',()=>{const s=apply(base(),{action:'approve',workItemId:order.id,note:'Internal draft only'}); assert.equal(s.workItems[0].status,'This Week');assert.equal(s.workItems[0].approval?.verdict,'approved');assert.equal(s.commandLog?.[0].actor,'Operator credential');assert.equal(s.commandLog?.[0].from,'Needs B Approval');});
test('reject returns to backlog with reason',()=>{const s=apply(base(),{action:'request-changes',workItemId:order.id,note:'Narrow scope'});assert.equal(s.workItems[0].status,'Backlog');assert.equal(s.workItems[0].approval?.verdict,'changes-requested');});
test('status shortcut cannot bypass approval',()=>assert.throws(()=>apply(base(),{action:'status',workItemId:order.id,status:'This Week'}),/approval/));
test('update cannot bypass approval',()=>assert.throws(()=>apply(base(),{action:'update',item:{...order,status:'This Week'}}),/Approve order/));
test('unknown action rejected',()=>assert.throws(()=>apply(base(),{action:'launch',workItemId:order.id}),/Unknown/));
test('missing target rejected',()=>assert.throws(()=>apply(base(),{action:'approve',workItemId:'missing',note:'ok'}),/no longer/));
test('scope edits invalidate approval',()=>{const s=apply(base(),{action:'approve',workItemId:order.id,note:'ok'});const next=applyCommandAction(s,{action:'update',item:{...s.workItems[0],owner:'Athena'}},'2026-09-15T04:01:00Z','next');assert.equal(next.workItems[0].status,'Needs B Approval');assert.equal(next.workItems[0].approval,undefined);});
test('request changes cannot be bypassed through status',()=>{const s=apply(base(),{action:'request-changes',workItemId:order.id,note:'revise'});assert.throws(()=>applyCommandAction(s,{action:'status',workItemId:order.id,status:'In Progress'},'now','next'),/revised order/);});
test('completion requires evidence',()=>{const s=base();s.workItems[0].status='In Progress';assert.throws(()=>apply(s,{action:'update',item:{...s.workItems[0],status:'Done'}}),/evidence/);});
test('completion preserves timestamp on subsequent edit',()=>{const s=base();s.workItems[0].status='In Progress';const next=apply(s,{action:'update',item:{...s.workItems[0],status:'Done',completionEvidence:'Test evidence'}});const after=applyCommandAction(next,{action:'update',item:next.workItems[0]},'2026-09-15T05:00:00Z','next');assert.equal(after.workItems[0].completedAt,'2026-09-15T04:00:00.000Z');});
test('forged approval supplied by client is ignored',()=>{const s=base();s.workItems=[];const next=apply(s,{action:'create',item:{...order,status:'Backlog',approval:{verdict:'approved'}}});assert.equal(next.workItems[0].approval,undefined);});
test('duplicate creation rejected',()=>assert.throws(()=>apply(base(),{action:'create',item:order}),/already exists/));
test('prospecting lane supported',()=>{const s=base();s.workItems=[];const next=apply(s,{action:'create',item:{...order,lane:'Prospecting',owner:'Flint'}});assert.equal(next.workItems[0].lane,'Prospecting');});
test('input state not mutated',()=>{const s=base();const old=JSON.stringify(s);apply(s,{action:'approve',workItemId:order.id,note:'ok'});assert.equal(JSON.stringify(s),old);});
